WebApplication3/WebApplication3/Areas/Admin/Controllers/DanhMucController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication3.Authorize;
using WebApplication3.Server.DAO;
using WebApplication3.Server.EF;

namespace WebApplication3.Areas.Admin.Controllers
{
    //[AuthorizeUserAttribute]
    public class DanhMucController : Controller
    {
        DanhMucDAO categoryDAO = new DanhMucDAO();
        // GET: Admin/DanhMuc
        public ActionResult Index()
        {
            return View(categoryDAO.GetAll());
        }

        public ActionResult Them()
        {
            return View("Them");
        }

        [HttpPost]
        public ActionResult Them(TheLoai tl)
        {
            int res = categoryDAO.add(tl);
            if (res != -1)
            {
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Thêm danh mục xảy ra lỗi. Xin thử lại!");
            return View();
        }
        public ActionResult Sua(int id)
        {
            return View(categoryDAO.getCategoryById(id));
        }

        [HttpPost]
        public ActionResult Sua(TheLoai tl)
        {
            bool res = categoryDAO.update(tl);
            if (res)
            {
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Cập nhật xảy ra lỗi, vui lòng kiểm tra lại");
            return View();
        }

        public ActionResult Xoa(int id)
        {
            var res = categoryDAO.remove(id);
            if (res)
            {
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Xóa xảy ra lỗi, vui lòng kiểm tra lại");
            return View();
        }
    }
}

WebApplication3/WebApplication3/Areas/Admin/Controllers/DonHangsController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication3.Areas.Admin.ModelAdmin;
using WebApplication3.Authorize;
using WebApplication3.Server.EF;

namespace WebApplication3.Areas.Admin.Controllers
{
    [AuthorizeUserAttribute]
    public class DonHangsController : Controller
    {
        private PhongShopDB db = new PhongShopDB();

        public ActionResult UpdateStatus(int orderId, string status)
        {
            var _dh = new DonHang() { orderId = orderId, status = status };
            db.DonHangs.Attach(_dh);
            db.Entry(_dh).Property(X => X.status).IsModified = true;
            db.SaveChanges();
            return RedirectToAction("Details", new { id = orderId});
        }

        // GET: Admin/DonHangs
        public  ActionResult Index(string term, bool isSearchTerm = false, String Type = "all", int? page = 1)
        {
            int pageSize = 10;
            int pageNumber = page ?? 1;
            if (isSearchTerm)
            {
                var listOrders = db.DonHangs.ToList().Where(orderItem => orderItem.orderId == Convert.ToInt32(term)).Select(item =>
                {
                    item.customerName = db.KhachHangs.ToList().Where(kh =>
                    {

                        return kh.userId == item.userId;
                    }).Select(i => i.firstName).SingleOrDefault();
                    return item;
                }).ToPagedList(pageNumber, pageSize);
                return View(listOrders);
            }
            if (Type == "all")
            {
                var l = this.getOrderBaseStatus("all", pageNumber, pageSize);
                return View(l);
            } else if (Type == "pending")
            {
                var l = this.getOrderBaseStatus("pending", pageNumber, pageSize);
                return View(l);
            }
            else if (Type == "deliver")
            {
                var l = this.getOrderBaseStatus("deliver", pageNumber, pageSize);
                return View(l);
            }
            else if (Type == "delivered")
            {
                var l = this.getOrderBaseStatus("delivered", pageNumber, pageSize);
                return View(l);
            }
            else if (Type == "canceled")
            {
                var l = this.getOrderBaseStatus("canceled", pageNumber, pageSize);
                return View(l);
            }
            else
            {
                var l = this.getOrderBaseStatus("all", pageNumber, pageSize);
                return View(l);
            }
        }

        private IEnumerable<DonHang> getOrderBaseStatus(string status, int pageNumber, int pageSize)
        {
            if (status == "all")
            {
                return db.DonHangs.ToList().Select(item =>
                {
                    item.customerName = db.KhachHangs.ToList().Where(kh =>
                    {

                        return kh.userId == item.userId;
                    }).Select(i => i.firstName).SingleOrDefault();
                    return item;
                }).ToPagedList(pageNumber, pageSize);
            }
            return db.DonHangs.ToList().Where(i => i.status == status).Select(item =>
            {
                item.customerName = db.KhachHangs.ToList().Where(kh =>
                {

                    return kh.userId == item.userId;
                }).Select(i => i.firstName).SingleOrDefault();
                return item;
            }).ToPagedList(pageNumber, pageSize);
        } 

        // GET: Admin/DonHangs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var donHang = db.DonHangs.ToList().Where(order => order.orderId == id).Select(item => new DonHangViewModel() {
                customerName = db.KhachHangs.ToList().Where(kh => {
                    return kh.userId == item.userId;
                }).Select(i => i.firstName + " " + i.lastName).SingleOrDefault(),
                address = item.address,
                status = item.status,
                orderId = item.orderId,
                listOrders = db.ChiTietDonHangs.Where(product => product.orderId == item.orderId).ToList(),
                totalQuantity = db.ChiTietDonHangs.Where(product => product.orderId == item.orderId).Sum(i => i.quantity),
                totalMoney = db.ChiTietDonHangs.Where(product => product.orderId == item.orderId).Sum(i => i.price)
            }).SingleOrDefault();
            if (donHang == null)
            {
                return HttpNotFound();
            }
            return View(donHang);
        }

        // GET: Admin/DonHangs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/DonHangs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "orderId,customerId,address,note,status,discountId")] DonHang donHang)
        {
            if (ModelState.IsValid)
            {
                db.DonHangs.Add(donHang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(donHang);
        }

        // GET: Admin/DonHangs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonHang donHang = db.DonHangs.Find(id);
            if (donHang == null)
            {
                return HttpNotFound();
            }
            return View(donHang);
        }

        // POST: Admin/DonHangs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "orderId,customerId,address,note,status,discountId")] DonHang donHang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(donHang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(donHang);
        }

        // GET: Admin/DonHangs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonHang donHang = db.DonHangs.Find(id);
            if (donHang == null)
            {
                return HttpNotFound();
            }
            return View(donHang);
        }

        // POST: Admin/DonHangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DonHang donHang = db.DonHangs.Find(id);
            db.DonHangs.Remove(donHang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication3/WebApplication3/Areas/Admin/Controllers/SanPhamController.cs
using PagedList;
using System;
using System.Web;
using System.Web.Mvc;
using WebApplication3.Authorize;
using WebApplication3.Server.DAO;
using WebApplication3.Server.EF;

namespace WebApplication3.Areas.Admin.Controllers
{
    [AuthorizeUserAttribute]
    public class SanPhamController : Controller
    {
        SanPhamDAO SanPhamDAO = new SanPhamDAO();
        public ActionResult Index(int? page)
        {
            int pageSize = 10;
            int pageNumber = page ?? 1;
            return View(SanPhamDAO.GetAll().ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Them()
        {
            var dm = new DanhMucDAO();
            ViewBag.Categories = dm.GetAll();
            return View("Them");
        }


        [HttpPost]
        public ActionResult Them(SanPham g, HttpPostedFileBase image)
        {
            if (image != null)
            {
                image.SaveAs((HttpContext.Server.MapPath("~/Images/")+ image.FileName));
                g.image = image.FileName;
            } 
            int res = SanPhamDAO.add(g);
            if (res != -1)
            {
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Thêm giày xảy ra lỗi. Xin thử lại!");
            return View();
        }


        public ActionResult Sua(int id)
        {
            SanPham entity = SanPhamDAO.getShoeById(id);
            var dm = new DanhMucDAO();
            ViewBag.Categories = dm.GetAll();
            return View(entity);
        }
        [HttpPost]
        public ActionResult Sua(SanPham g, HttpPostedFileBase imageEdit)
        {
            if (imageEdit != null)
            {
                byte[] img = new byte[imageEdit.ContentLength];
                //image.InputStream.Read(img, 0, image.ContentLength);
                imageEdit.SaveAs((HttpContext.Server.MapPath("~/Images/") + imageEdit.FileName));
                g.image = imageEdit.FileName;
            }
            bool res = SanPhamDAO.edit(g, false);
            if (res)
            {
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Cập nhật xảy ra lỗi. Xin kiểm tra lại!");
            return View();
        }

        public ActionResult Xoa(int id)
        {
            SanPham entity = SanPhamDAO.getShoeById(id);
            var res = SanPhamDAO.edit(entity, true);
            if (!res)
            {
                ModelState.AddModelError("", "Xóa khách hàng xảy ra lỗi. Xin thử lại!");
                return View();
            }
            return RedirectToAction("Index");
        }
    }
}

WebApplication3/WebApplication3/Areas/Admin/Controllers/SlideNewProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication3.Server.DAO;
using WebApplication3.Server.EF;

namespace WebApplication3.Areas.Admin.Controllers
{
    public class SlideNewProductController : Controller
    {
        //SanPhamDAO giayDAO = new SanPhamDAO();
        //SlideNewProductDAO sl = new SlideNewProductDAO();
        //// GET: Admin/SlideNewProduct
        //public ActionResult Index()
        //{
        //    return View(sl.GetAll());
        //}

        //public ActionResult Them()
        //{
        //    return View(giayDAO.GetAll().Where(item => {
        //        var d = DateTime.Now;
        //        return item.createdAt < d;
        //    }).Take(20));
        //}

        //public ActionResult ThemSlide(int id)
        //{
        //    var giay = giayDAO.getShoeById(id);
        //    SlideNewProduct entity = new SlideNewProduct();
        //    entity.shoeId = id;
        //    entity.createdAt = DateTime.Now;
        //    entity.isActive = true;
        //    entity.title = giay.shoeName;
        //    var res = sl.Them(entity);
        //    if (res < 0)
        //    {
        //        ModelState.AddModelError("", "Thêm slide xảy ra lỗi. Xin thử lại!");
        //    }
        //    return RedirectToAction("Them");
        //}

        //public ActionResult Xoa(int id)
        //{
        //    var res = sl.Xoa(id);
        //    if (!res)
        //    {
        //        ModelState.AddModelError("", "Thêm slide xảy ra lỗi. Xin thử lại!");
        //    }
        //    return RedirectToAction("Index");
        //}

        //public ActionResult UnSelected(int id)
        //{
        //    var res = sl.Xoa(id);
        //    if (!res)
        //    {
        //        ModelState.AddModelError("", "Thêm slide xảy ra lỗi. Xin thử lại!");
        //    }
        //    return RedirectToAction("Them");
        //}
    }
}

WebApplication3/WebApplication3/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello</title>
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Assets/admin/plugins/fontawesome-free/css/all.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="~/Assets/admin/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/Assets/admin/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/Assets/admin/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Assets/admin/css/adminlte.min.css">
    <link rel="stylesheet" href="~/Assets/admin/css/admin.style.css">
    <link href="~/Assets/client/css/paginator.css" rel="stylesheet" />
    <meta charset="UTF-8" />
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <!-- Navbar -->
        @*<nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            @*<ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
            </ul>*@

            <!-- SEARCH FORM -->
            @*<form class="form-inline ml-3">
                <div class="input-group input-group-sm">
                    <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                    <div class="input-group-append">
                        <button class="btn btn-navbar" type="submit">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>*@

        @*</nav>*@
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="../index3.html" class="brand-link">
                <img src="~/Assets/admin/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">Admin Phong</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                </div>


                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                        with font-awesome or any other icon font library -->
                        <li class="nav-item">
                            <a href="@Url.Action("Index", "Home")" class="nav-link">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    Bảng điều khiển
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index", "DanhMuc")" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    Danh mục hãng điện thoại
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index", "SanPham")" class="nav-link">
                                <i class="nav-icon fas fa-shoe-prints"></i>
                                <p>
                                    Sản phẩm điện thoại
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index", "KhachHang") " class="nav-link">
                                <i class="nav-icon fas fa-chart-pie"></i>
                                <p>
                                    Tài khoản
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index", "DonHangs") " class="nav-link">
                                <i class="nav-icon fas fa-percentage"></i>
                                <p>
                                    Đơn hàng
                                </p>
                            </a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link">
                                <i class="nav-icon fab fa-sellsy"></i>
                                <p>
                                    Slide Top Bán chạy
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "SlideNewProduct") ">
                                <i class="nav-icon fab fa-sellcast"></i>
                                <p>
                                    Slide Sản phẩm mới
                                </p>
                            </a>
                        </li>*@
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper" style="min-height: calc(100vh - 58px) !important">
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1>@ViewBag.Title</h1>
                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>
            <!-- Main content -->
            <section class="content" style="padding-bottom: 2rem;">
                @RenderBody()
            </section>
            <!-- /.content -->
        </div>
    </div>
    <script src="~/Assets/admin/plugins/jquery/jquery.min.js"></script>

    <script src="~/Assets/admin/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Assets/admin/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/Assets/admin/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/Assets/admin/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/Assets/admin/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/Assets/admin/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/Assets/admin/plugins/jszip/jszip.min.js"></script>
    <script src="~/Assets/admin/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/Assets/admin/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/Assets/admin/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/Assets/admin/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/Assets/admin/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
    <script src="~/Assets/admin/js/adminlte.min.js"></script>
    <script src="~/Assets/admin/plugins/moment/moment.min.js"></script>
    <script src="~/Assets/admin/plugins/inputmask/jquery.inputmask.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/Assets/admin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <!-- bs-custom-file-input -->
    <script src="~/Assets/admin/plugins/bs-custom-file-input/bs-custom-file-input.min.js"></script>

    @RenderSection("scripts", required: false)
    <script src="~/Assets/admin/js/demo.js"></script>
    <!-- Page specific script -->
</body>
</html>