WebApplication3/WebApplication3/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication3.Server.DAO;

namespace WebApplication3.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        public ActionResult Index()
        {
            DanhMucDAO dm = new DanhMucDAO();
            ViewBag.danhMuc = dm.GetAll().ToList();
            return View();
        }
    }
}

WebApplication3/WebApplication3/Controllers/PaymentMethodController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication3.Server.DAO;
using WebApplication3.Server.EF;

namespace WebApplication3.Controllers
{
    public class PaymentMethodController : Controller
    {
        // GET: PaymentMethod
        public ActionResult Checkout()
        {
            DiscountDAO dc = new DiscountDAO();
            ViewBag.discountList = dc.GetAll();
            var userId = System.Web.HttpContext.Current.Session["USER_ID"];
            if (userId != null)
            {
                return View();
            }
            Session.Add("NOT_LOGGED_IN", true);
            return RedirectToAction("Index", "Account");
        }

        public ActionResult Payment(String address)
        {
            DiscountDAO dc = new DiscountDAO();
            ViewBag.discountList = dc.GetAll();
            Session.Add("ADDRESS", address);
            return View();
        }
        private HttpContextBase Context { get; set; }
        [HttpPost]
        public ActionResult Payment(ICollection<ChiTietDonHang> list)
        {
            DonHang dh = new DonHang();
            DonHangDAO dhDAO = new DonHangDAO();
            dh.userId = Convert.ToInt32(System.Web.HttpContext.Current.Session["USER_ID"]);
            dh.address = Convert.ToString(System.Web.HttpContext.Current.Session["ADDRESS"]);
            dh.ChiTietDonHangs = list;
            dh.status = "pending";
            dh.createdAt = DateTime.Now;
            dhDAO.them(dh);
            DiscountDAO dc = new DiscountDAO();
            ViewBag.discountList = dc.GetAll();
            return Content("ok na");
        }
    }
}

WebApplication3/WebApplication3/Views/PaymentMethod/Checkout.cshtml
@using PagedList.Mvc;
@{
    Layout = "~/Views/_Shared/_LayoutCheckout.cshtml";
}


<h4 class="mb-3">Thông tin Thanh toán</h4>
<div class="checkout-info__address">
    <div class="form-group">
        <label for="phone">Địa chỉ giao hàng</label>
        <input type="text" class="form-control" id="address" value="@Request.QueryString["address"]" placeholder="Địa chỉ">

    </div>
    <div class="form-group">
        <label for="name">Tên</label>
        <input type="text" class="form-control" id="name" placeholder="Tên" value="@Request.QueryString["firstname"]">
    </div><div class="form-group">
        <label for="name">Họ</label>
        <input type="text" class="form-control" id="name" placeholder="Họ" value="@Request.QueryString["lastName"]">
    </div>
    @*<div class="form-group">
        <label for="exampleInputEmail1">Email</label>
        <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email" value="@Request.QueryString["email"]">

    </div>*@
    @*<div class="form-group">
        <label for="phone">Điện thoại</label>
        <input type="text" class="form-control" id="phone" value="@Request.QueryString["phone"]" placeholder="Điện thoại">

    </div>*@
    @*<div class="form-group">
            <label for="province">Tỉnh</label>
            <input type="text" class="form-control" id="province" value="@Request.QueryString["province"]" placeholder="Tỉnh">

        </div>
        <div class="form-group">
            <label for="district">Quận/Huyện</label>
            <input type="text" class="form-control" id="district" value="@Request.QueryString["district"]" placeholder="Quận/Huyện">

        </div>
        <div class="form-group">
            <label for="com">Xã/Phường</label>
            <input type="text" class="form-control" id="com" value="@Request.QueryString["commune"]" placeholder="Xã/Phường">

        </div>*@
</div>

<div class="checkout-action d-flex justify-content-between">
    <a href="@Url.Action("Index", "Cart")"><i class="fas fa-angle-left"></i> <span>Giỏ hàng</span> </a>
    @*<a href="@Url.Action("Payment", "PaymentMethod", new {address = docume })" class="btn btn-primary">Phương thức thanh toán</a>*@
    @*<button id="btnRedirect" type="button" class="btn btn-primary">Phương thức thanh toán</button>*@
    @Html.ActionLink("Phương thức thanh toán", "Payment", "PaymentMethod", new { address ="xxx", TypeId = "1" }, new { @id = "link" })

</div>


@section scripts {
    <script>
        $('#link').click(function () {
            this.href = this.href.replace("xxx", $("#address").val().trim());
        });
    </script>
} 

WebApplication3/WebApplication3/Views/PaymentMethod/Payment.cshtml
@{
    ViewBag.Title = "Payment";
    Layout = "~/Views/_Shared/_LayoutCheckout.cshtml";
}



<h2 class="mb-4">Đặt hàng</h2>
<div class="checkout-info__address">
    <div class="mb-5">
        <h5 class="mb-3 font-weight-normal">Phương thức vận chuyển</h5>
        <div class="pt-3 pb-3 pl-2 pr-2"  style="border:1px solid #eee">
            <div class="d-flex justify-content-between">
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
                    <label class="form-check-label" for="exampleRadios1">
                        Giao hàng tận nơi
                    </label>
                </div>
                <div><span class="font-weight-normal">40,000.00</span> <span style="text-decoration: underline; font-weight: 500;">đ</span></div>
            </div>

        </div>
    </div>

    <div class="mb-4">
        <h5 class="mb-3 font-weight-normal">Phương thức thanh toán</h5>
        <div class="pt-3 pb-3 pl-2 pr-2" style="border:1px solid #eee">
            <div class="d-flex justify-content-between">
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="cod" id="cod" value="receive" checked>
                    <label class="form-check-label" for="cod">
                        Thanh toán khi giao hàng (COD)
                    </label>
                </div>
            </div>

        </div>
        @*<div class="pt-3 pb-3 pl-2 pr-2" style="border:1px solid #eee">
            <div class="d-flex justify-content-between">
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="cod" id="bank" value="bank" checked>
                    <label class="form-check-label" for="bank">
                        Chuyển khoản qua ngân hàng
                    </label>
                </div>
            </div>

        </div>*@
    </div>
</div>

<div class="checkout-action d-flex justify-content-between">
    <a href="@Url.Action("Index", "Cart")"><i class="fas fa-angle-left"></i> <span>Trở lại thông tin vận chuyển</span> </a>
    <button type="button" class="btn btn-primary" onclick="order()">Đặt hàng</button>
</div>

@section scripts {
    <script>
        function order() {
            fetch('https://localhost:44385/PaymentMethod/Payment', {
                method: 'POST',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({ list: JSON.parse(localStorage.getItem("giohang")) })
            }).then((res) => {
                localStorage.removeItem("giohang");
                console.log("res: ", res);
                if (res.status == "200") {
                    window.location.href = '@Url.Action("Index", "Home")';
                }
            }).catch(err => console.log(err));
        }
    </script>    
}